services:
  - type: web
    name: IOT_Project
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python websocket_server.py
    envVars:
      - key: PORT
        value: 5000
